import React, { useEffect, useId, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Coffee, FileText, LayoutDashboard, Menu, Plus, Search, ShieldCheck, Sparkles, Sun, Users, X } from 'lucide-react';
import './styles.css';

const iso = date => date.toISOString().slice(0, 10);
const dateObject = value => new Date(`${value}T12:00:00Z`);
const add = (value, count) => iso(new Date(dateObject(value).getTime() + count * 86400000));
const dayCount = segments => segments.reduce((sum, s) => sum + (s.start && s.end && s.end >= s.start ? Math.round((dateObject(s.end) - dateObject(s.start)) / 86400000) + 1 : 0), 0);
const fmt = (date, options = { month: 'short', day: 'numeric' }) => dateObject(date).toLocaleDateString('en-US', { ...options, timeZone: 'UTC' });
const range = segments => {
  const includeYear = segments.some(s => s.start.slice(0, 4) !== String(new Date().getUTCFullYear()) || s.end.slice(0, 4) !== s.start.slice(0, 4));
  const options = { month: 'short', day: 'numeric', ...(includeYear ? { year: 'numeric' } : {}) };
  return segments.map(s => s.start === s.end ? fmt(s.start, options) : `${fmt(s.start, options)} – ${fmt(s.end, options)}`).join(' · ');
};
const initials = name => name.split(' ').map(n => n[0]).slice(0, 2).join('');
const label = value => value === 'hr' ? 'HR' : value[0].toUpperCase() + value.slice(1);

async function api(path, user, body) {
  const response = await fetch(`/api${path}`, { headers: { 'Content-Type': 'application/json', 'X-Demo-User': user }, ...(body !== undefined ? { method: 'POST', body: JSON.stringify(body) } : {}) });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Unable to complete this action.');
  return data;
}
function Avatar({ person, small = false }) { return <span className={`avatar ${small ? 'small' : ''}`} style={{ background: person?.color || '#dfe6d9' }}>{person ? initials(person.name) : '?'}</span>; }
function Status({ value }) { return <span className={`status ${value}`}><span />{value === 'pending' ? 'Pending approval' : label(value)}</span>; }
function Empty({ title, children }) { return <div className="empty"><CalendarDays size={29} /><h3>{title}</h3><p>{children}</p></div>; }

function Modal({ title, subtitle, children, close }) {
  const ref = useRef(null);
  const titleId = useId();
  useEffect(() => {
    const before = document.activeElement;
    ref.current.showModal();
    return () => { if (before instanceof HTMLElement) before.focus(); };
  }, []);
  return <dialog ref={ref} aria-labelledby={titleId} className="modal" onCancel={event => { event.preventDefault(); close(); }} onClick={event => { if (event.target === ref.current) close(); }}>
    <div className="modal-head"><div><span className="eyebrow">YOUR TIME, WELL SPENT</span><h2 id={titleId}>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={20} /></button></div>
    {children}
  </dialog>;
}

function RequestForm({ workspace, original, close, submit }) {
  const tomorrow = add(workspace.today, 1);
  const [segments, setSegments] = useState(original ? original.segments.map(s => ({ ...s })) : [{ start: '', end: '' }]);
  const [note, setNote] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const days = dayCount(segments);
  const additional = original ? Math.max(0, days - dayCount(original.segments)) : days;
  const manager = workspace.people.find(p => p.id === workspace.user.manager_id);
  async function onSubmit(event) {
    event.preventDefault(); setError(''); setBusy(true);
    try { await submit({ segments, note, ...(original ? { replacesId: original.id } : {}) }); }
    catch (error) { setError(error.message); setBusy(false); }
  }
  return <Modal title={original ? 'Reschedule your leave' : 'Make time for yourself'} subtitle={original ? 'Your approved dates stay in place until the change is approved.' : 'Choose your dates. We’ll take care of the day counting.'} close={() => !busy && close()}>
    <form onSubmit={onSubmit}>
      <div className="form-balance"><Sun size={22} /><span>Available balance</span><strong>{workspace.balance.available.toFixed(2)} days</strong></div>
      <div className="segments">{segments.map((segment, index) => <div className="segment" key={index}><div className="segment-heading">{segments.length > 1 ? `Segment ${index + 1}` : 'Vacation dates'}{segments.length > 1 && <button type="button" className="text-button" onClick={() => setSegments(segments.filter((_, i) => i !== index))}>Remove</button>}</div><div className="date-fields"><label>Start date<input aria-label={`Start date ${index + 1}`} type="date" min={tomorrow} required value={segment.start} onInput={e => setSegments(segments.map((s, i) => i === index ? { ...s, start: e.target.value } : s))} /></label><span>→</span><label>End date<input aria-label={`End date ${index + 1}`} type="date" min={segment.start || tomorrow} required value={segment.end} onInput={e => setSegments(segments.map((s, i) => i === index ? { ...s, end: e.target.value } : s))} /></label></div></div>)}</div>
      {segments.length < 30 && <button type="button" className="text-button add-segment" onClick={() => setSegments([...segments, { start: '', end: '' }])}><Plus size={16} /> Add another segment</button>}
      <label className="note-label">Note for your manager <span>(optional)</span><textarea maxLength={1000} value={note} onInput={e => setNote(e.target.value)} placeholder="Anything your manager should know?" rows={3} /></label>
      <div className="request-summary"><div><span>Total leave</span><strong>{days} calendar {days === 1 ? 'day' : 'days'}</strong></div><div><span>{original ? 'Additional days reserved' : 'Balance after request'}</span><strong className={additional > workspace.balance.available ? 'danger-text' : ''}>{original ? additional : (workspace.balance.available - days).toFixed(2)} days</strong></div></div>
      <p className="form-hint"><ShieldCheck size={16} /> Sent to {manager?.name || 'your assigned manager'} for approval. Weekends count as leave days.</p>
      {error && <p className="form-error" role="alert">{error}</p>}
      <div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>Keep planning</button><button className="button primary" disabled={busy || additional > workspace.balance.available}>{busy ? 'Submitting…' : original ? 'Request new dates' : 'Submit request'}<ArrowRight size={17} /></button></div>
    </form>
  </Modal>;
}

function ReviewForm({ request, person, close, submit }) {
  const [comment, setComment] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  async function review(status) { setBusy(true); setError(''); try { await submit({ status, comment }); } catch (error) { setError(error.message); setBusy(false); } }
  return <Modal title="Review leave request" subtitle={`${person.name} · ${person.team}`} close={() => !busy && close()}><div className="review-dates"><CalendarDays size={22} /><div><strong>{range(request.segments)}</strong><p>{dayCount(request.segments)} calendar days{request.replaces_id ? ' · Schedule change' : ''}</p></div></div>{request.note && <blockquote>{request.note}</blockquote>}<form onSubmit={e => { e.preventDefault(); review('approved'); }}><label className="note-label">Your comment<textarea autoFocus required maxLength={1000} rows={3} placeholder="Let them know about your decision…" value={comment} onInput={e => setComment(e.target.value)} /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button danger" disabled={busy || !comment.trim()} onClick={() => review('rejected')}>Reject request</button><button className="button primary" disabled={busy || !comment.trim()}><Check size={17} />{busy ? 'Saving…' : 'Approve request'}</button></div></form></Modal>;
}

function Calendar({ workspace, compact = false, company = false }) {
  const [month, setMonth] = useState(workspace.today.slice(0, 7));
  const [team, setTeam] = useState('All teams');
  const [selected, setSelected] = useState(null);
  const start = `${month}-01`;
  const first = dateObject(start);
  const year = first.getUTCFullYear(), monthNumber = first.getUTCMonth();
  const count = new Date(Date.UTC(year, monthNumber + 1, 0)).getUTCDate();
  const offset = (first.getUTCDay() + 6) % 7;
  const slots = Array.from({ length: Math.ceil((offset + count) / 7) * 7 }, (_, i) => add(start, i - offset));
  const people = Object.fromEntries(workspace.people.map(p => [p.id, p]));
  const eventsOn = date => workspace.calendar.filter(r => (team === 'All teams' || people[r.employee_id]?.team === team) && r.segments.some(s => date >= s.start && date <= s.end));
  function move(amount) { setMonth(iso(new Date(Date.UTC(year, monthNumber + amount, 1))).slice(0, 7)); setSelected(null); }
  return <section className={`panel calendar-panel ${compact ? 'compact' : ''}`}><div className="panel-heading"><div><h2>{company ? 'Company calendar' : 'Team calendar'}</h2>{!compact && <p>Plan together. See who’s taking time off.</p>}</div>{!compact && company && <label className="sr-only" htmlFor="team-filter">Filter by team</label>}{!compact && company && <select id="team-filter" value={team} onChange={e => setTeam(e.target.value)}>{['All teams', ...new Set(workspace.people.map(p => p.team))].map(t => <option key={t}>{t}</option>)}</select>}</div>
    <div className="calendar-toolbar"><strong>{fmt(start, { month: 'long', year: 'numeric' })}</strong><div><button className="text-button today-button" onClick={() => { setMonth(workspace.today.slice(0, 7)); setSelected(workspace.today); }}>Today</button><button className="icon-button" aria-label="Previous month" onClick={() => move(-1)}><ChevronLeft size={17} /></button><button className="icon-button" aria-label="Next month" onClick={() => move(1)}><ChevronRight size={17} /></button></div></div>
    <div className="calendar-grid weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => <span key={d}>{compact ? d[0] : d}</span>)}</div>
    <div className="calendar-grid dates">{slots.map(date => { const events = eventsOn(date); return <button key={date} className={`calendar-day ${date.slice(0, 7) !== month ? 'outside' : ''} ${date === workspace.today ? 'is-today' : ''} ${date === selected ? 'selected' : ''}`} aria-label={`${fmt(date, { month: 'long', day: 'numeric', year: 'numeric' })}, ${events.length} away`} onClick={() => setSelected(date)}><span className="day-number">{Number(date.slice(-2))}</span>{compact ? <span className="event-dots">{events.slice(0, 3).map(r => <i key={r.id} style={{ background: people[r.employee_id]?.color }} />)}</span> : <span className="calendar-events">{events.slice(0, 2).map(r => <span key={r.id} style={{ background: `${people[r.employee_id]?.color}55`, borderColor: people[r.employee_id]?.color }}>{people[r.employee_id]?.name.split(' ')[0]}</span>)}{events.length > 2 && <small>+{events.length - 2} more</small>}</span>}</button>; })}</div>
    {selected ? <div className="day-detail"><strong>{fmt(selected, { month: 'long', day: 'numeric' })}</strong>{eventsOn(selected).length ? eventsOn(selected).map(r => <div key={r.id}><Avatar person={people[r.employee_id]} small /><span>{people[r.employee_id]?.name}</span><span className="muted">On leave</span></div>) : <p>No approved leave. The team is all here.</p>}</div> : <div className="calendar-legend"><span><i className="legend-dot" /> Approved leave</span><span>Click a day to see who’s away</span></div>}
  </section>;
}

function App() {
  const [userId, setUserId] = useState('alex');
  const [accounts, setAccounts] = useState([]);
  const [workspace, setWorkspace] = useState(null);
  const [page, setPage] = useState('overview');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null);
  const [toast, setToast] = useState('');
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const [actionBusy, setActionBusy] = useState(false);
  const requestGeneration = useRef(0);
  async function refresh() { const generation = ++requestGeneration.current; try { const data = await api('/workspace', userId); if (generation === requestGeneration.current) { setWorkspace(data); setError(''); } } catch (error) { if (generation === requestGeneration.current) setError(error.message); } finally { if (generation === requestGeneration.current) setLoading(false); } }
  useEffect(() => { api('/accounts', userId).then(setAccounts).catch(error => setError(error.message)); }, []);
  useEffect(() => { setLoading(true); setWorkspace(null); refresh(); }, [userId]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 5000); return () => clearTimeout(timer); } }, [toast]);
  function navigate(target) { setPage(target); setFilter('all'); setSearch(''); setMobileNav(false); }
  function switchUser(id) { setUserId(id); navigate('overview'); setModal(null); }
  async function mutation(path, body, message) { await api(path, userId, body); setModal(null); await refresh(); setToast(message); }
  if (!workspace) return <main className="startup"><div className="brand-mark"><Sun /></div><h1>Otpusk<span>®</span></h1>{loading ? <p>Making room for your next break…</p> : <><p role="alert">{error || 'Could not load the workspace.'}</p><button className="button primary" onClick={() => { setLoading(true); refresh(); }}>Try again</button></>}</main>;
  const { user, people, requests, balance, today } = workspace;
  const ownRequests = requests.filter(r => r.employee_id === user.id);
  const pending = requests.filter(r => r.status === 'pending' && people.find(p => p.id === r.employee_id)?.manager_id === user.id && r.employee_id !== user.id);
  const upcoming = ownRequests.filter(r => r.status === 'approved' && r.segments[0].start > today).sort((a, b) => a.segments[0].start.localeCompare(b.segments[0].start))[0];
  const away = workspace.calendar.filter(r => r.segments.some(s => s.start <= today && s.end >= today));
  const manager = people.find(p => p.id === user.manager_id);
  const nav = [
    { id: 'overview', label: 'Overview', icon: LayoutDashboard },
    { id: 'requests', label: 'My requests', icon: FileText },
    { id: 'calendar', label: 'Team calendar', icon: CalendarDays },
    ...(user.role === 'manager' ? [{ id: 'approvals', label: 'Approvals', icon: CheckCheck, count: pending.length }] : []),
    ...(user.role === 'hr' ? [{ id: 'hr', label: 'HR dashboard', icon: Users }] : []),
  ];
  const pageNames = { overview: 'Overview', requests: 'My requests', calendar: 'Team calendar', approvals: 'Approvals', hr: 'HR dashboard', profile: 'My profile', policy: 'Leave policy' };
  const personFor = id => people.find(p => p.id === id);
  function requestRows(list, review = false) {
    return list.map(r => { const isFuture = r.segments[0].start > today; const changePending = requests.some(child => child.replaces_id === r.id && child.status === 'pending'); return <div className="request-row" key={r.id}><div className="request-symbol">{review ? <Avatar person={personFor(r.employee_id)} /> : <Sun size={20} />}</div><div className="request-info"><strong>{review ? personFor(r.employee_id)?.name : r.replaces_id ? 'Schedule change' : 'Vacation leave'}</strong><span>{range(r.segments)}</span>{r.segments.length > 1 && <small>{r.segments.length} segments</small>}</div><span className="request-days">{dayCount(r.segments)} <span>days</span></span><Status value={r.status} /><div className="request-actions">{review ? <button className="button secondary small-button" onClick={() => setModal({ type: 'review', request: r })}>Review<ArrowUpRight size={15} /></button> : <button className="icon-button" aria-label={`View ${range(r.segments)} request`} onClick={() => setModal({ type: 'detail', request: r, isFuture, changePending })}><ArrowUpRight size={18} /></button>}</div></div>; });
  }
  return <div className="app-shell">
    {mobileNav && <button className="nav-backdrop" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><a className="brand" href="#overview" onClick={e => { e.preventDefault(); navigate('overview'); }}><span className="brand-mark"><Sun size={25} strokeWidth={1.7} /></span>otpusk<span className="brand-period">.</span></a><div className="workspace-label"><span className="studio-icon">F</span><div><strong>{workspace.company.name}</strong><span>Team workspace</span></div></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'active' : ''}`} onClick={() => navigate(item.id)}><item.icon size={19} strokeWidth={1.7} /><span>{item.label}</span>{item.count > 0 && <span className="nav-count">{item.count}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="balance-note"><Sun size={24} strokeWidth={1.4} /><strong>A little time off.<br />A lot to come back to.</strong><p>Your next chapter can wait<br />a few days.</p><button className="text-button" onClick={() => setModal({ type: 'request' })}>Plan your break <ArrowUpRight size={15} /></button></div><button className={`nav-item ${page === 'policy' ? 'active' : ''}`} onClick={() => navigate('policy')}><CircleHelp size={19} />Leave policy</button><a className="nav-item" href="/api/decision-log" download><ArrowDownToLine size={19} />Decision journal</a><button className="sidebar-profile" onClick={() => navigate('profile')}><Avatar person={user} /><span><strong>{user.name}</strong><small>{user.title}</small></span><ChevronRight size={17} /></button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={22} /></button><span>Workspace</span><ChevronRight size={14} /><strong>{pageNames[page]}</strong></div><div className="topbar-right"><span className="demo-tag">Demo workspace</span><label className="account-switch"><Avatar person={user} small /><select aria-label="Switch demo account" value={userId} onChange={e => switchUser(e.target.value)}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} · {label(a.role)}</option>)}</select><ChevronDown size={15} /></label></div></header>
    <main className="main-content">{error && <div className="error-banner" role="alert">{error}<button className="text-button" onClick={refresh}>Retry</button></div>}
      <div className="page-heading"><div><div className="eyebrow">{page === 'overview' ? fmt(today, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) : 'A LITTLE PLANNING. MORE PEACE OF MIND.'}</div><h1>{page === 'overview' ? <>Room for a little time off, {user.name.split(' ')[0]}<span className="heading-dot">.</span></> : pageNames[page]}</h1><p>{({ overview: 'A clear view of your time off, and the people around you.', requests: 'Your plans, past and upcoming. All in one place.', calendar: 'Make space for your plans, together.', approvals: 'Help your team make time for what matters.', hr: 'A little clarity for the whole company.', profile: 'The details behind your leave entitlement.', policy: 'Simple rules, so you can focus on making plans.' })[page]}</p></div>{!['policy', 'profile', 'approvals'].includes(page) && <button className="button primary request-cta" onClick={() => setModal({ type: 'request' })}><Plus size={18} />Request time off</button>}</div>
      {page === 'overview' && <>
        <section className="stat-grid"><article className="balance-card"><div className="stat-top"><span>Available leave</span><Sun size={22} strokeWidth={1.5} /></div><div className="balance-number">{balance.available.toFixed(2)}<span>days</span></div><div className="balance-progress"><span style={{ width: `${Math.min(100, Math.max(0, balance.available / Math.max(balance.accrued, 1) * 100))}%` }} /></div><div className="balance-foot"><span>Yours to make plans with</span><ArrowUpRight size={16} /></div></article><article className="stat-card"><div className="stat-top"><span>Accrued to date</span><Sparkles size={19} /></div><div className="stat-number">{balance.accrued.toFixed(2)}<span>days</span></div><p><span className="tiny-dot" />28 days a year, earned daily</p></article><article className="stat-card"><div className="stat-top"><span>Upcoming leave</span><CalendarDays size={19} /></div><div className="stat-number">{balance.approved}<span>days</span></div><p>{upcoming ? range(upcoming.segments) : 'Your next break starts with a plan'}</p></article><article className="stat-card"><div className="stat-top"><span>Awaiting approval</span><Clock3 size={19} /></div><div className="stat-number">{ownRequests.filter(r => r.status === 'pending').length}<span>{ownRequests.filter(r => r.status === 'pending').length === 1 ? 'request' : 'requests'}</span></div><p>{balance.pending} days reserved for your plans</p></article></section>
        <div className="overview-columns"><div className="overview-left"><section className="next-break"><div className="next-break-icon"><Coffee size={33} strokeWidth={1.2} /></div><div><span className="eyebrow">{upcoming ? 'YOUR NEXT RESET' : 'SOMETHING TO LOOK FORWARD TO'}</span><h2>{upcoming ? 'A change of pace is on the calendar.' : 'Good things happen after a break.'}</h2><p>{upcoming ? <>{range(upcoming.segments)} <span>·</span> {dayCount(upcoming.segments)} days to switch off</> : 'Choose a few days to slow down and recharge.'}</p></div><button className="icon-button" aria-label="View upcoming leave" onClick={() => upcoming ? setModal({ type: 'detail', request: upcoming, isFuture: true, changePending: requests.some(r => r.replaces_id === upcoming.id && r.status === 'pending') }) : setModal({ type: 'request' })}><ArrowUpRight size={21} /></button></section><section className="panel requests-panel"><div className="panel-heading"><h2>My requests <span className="count-pill">{ownRequests.length}</span></h2><button className="text-button" onClick={() => navigate('requests')}>View all <ArrowRight size={15} /></button></div><div className="requests-list">{ownRequests.length ? requestRows(ownRequests.slice(0, 4)) : <Empty title="Your plans start here">Request a few days off whenever you’re ready.</Empty>}</div></section><section className="panel team-panel"><div className="panel-heading"><h2>Who’s away today <span className="count-pill">{away.length}</span></h2><span className="muted">{fmt(today)}</span></div>{away.length ? <div className="away-people">{away.map(r => { const p = personFor(r.employee_id); const segment = r.segments.find(s => s.start <= today && s.end >= today); return <div className="away-person" key={r.id}><Avatar person={p} /><div><strong>{p?.name}</strong><span>{p?.team} <span>·</span> Back {fmt(add(segment.end, 1))}</span></div><span className="away-label">On leave</span></div>; })}</div> : <div className="all-here"><Users size={22} /><span>The team is all here today.</span></div>}</section></div><div className="overview-right"><Calendar workspace={workspace} compact /><section className="policy-card"><div className="policy-card-title"><ShieldCheck size={20} /><strong>Time off, without the guesswork</strong></div><p>You earn 28 calendar days each year. Unused days stay yours, and you can split your leave into smaller breaks.</p><button className="text-button" onClick={() => navigate('policy')}>Get to know your leave policy <ArrowUpRight size={15} /></button></section></div></div>
      </>}
      {page === 'requests' && <section className="panel"><div className="list-toolbar"><div className="tabs">{['all', 'pending', 'approved', 'past'].map(value => <button key={value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{value === 'all' ? 'All requests' : label(value)}</button>)}</div></div>{(() => { const list = ownRequests.filter(r => filter === 'all' || (filter === 'past' ? r.segments.every(s => s.end < today) || !['approved', 'pending'].includes(r.status) : r.status === filter)); return list.length ? requestRows(list) : <Empty title="Nothing here just yet">Your {filter === 'all' ? 'leave' : filter} requests will appear here.</Empty>; })()}</section>}
      {page === 'calendar' && <Calendar workspace={workspace} />}
      {page === 'approvals' && <><div className="approval-summary"><Clock3 size={20} /><strong>{pending.length} {pending.length === 1 ? 'request needs' : 'requests need'} your review</strong><span>A quick decision helps your team plan ahead.</span></div><section className="panel"><div className="panel-heading"><h2>Awaiting your decision</h2><span className="count-pill">{pending.length}</span></div>{pending.length ? requestRows(pending, true) : <Empty title="You’re all caught up">New requests from your direct reports will appear here.</Empty>}</section><section className="panel reviewed-panel"><div className="panel-heading"><h2>Review history</h2></div>{requests.filter(r => r.reviewed_by === user.id).length ? requestRows(requests.filter(r => r.reviewed_by === user.id)) : <Empty title="A fresh start">Your reviewed requests will appear here.</Empty>}</section></>}
      {page === 'hr' && <><div className="hr-stats"><div><span>People in the company</span><strong>{people.length}</strong></div><div><span>Away today</span><strong>{away.length}</strong></div><div><span>Awaiting manager review</span><strong>{requests.filter(r => r.status === 'pending').length}</strong></div></div><section className="panel employee-panel"><div className="panel-heading"><div><h2>Employee balances</h2><p>Accrued entitlement and committed time, at a glance.</p></div><label className="search-field"><Search size={17} /><input aria-label="Search employees" placeholder="Search people or teams" value={search} onInput={e => setSearch(e.target.value)} /></label></div><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Team</th><th>Accrued</th><th>Used</th><th>Upcoming</th><th>Reserved</th><th>Available</th></tr></thead><tbody>{people.filter(p => `${p.name} ${p.team}`.toLowerCase().includes(search.toLowerCase())).map(p => <tr key={p.id}><td><div className="table-person"><Avatar person={p} small /><div><strong>{p.name}</strong><span>{p.title}</span></div></div></td><td>{p.team}</td><td>{p.balance.accrued.toFixed(2)}</td><td>{p.balance.used}</td><td>{p.balance.approved}</td><td>{p.balance.pending}</td><td><strong className="available-pill">{p.balance.available.toFixed(2)} days</strong></td></tr>)}</tbody></table></div>{!people.some(p => `${p.name} ${p.team}`.toLowerCase().includes(search.toLowerCase())) && <Empty title="No matching people">Try a different name or team.</Empty>}</section><Calendar workspace={workspace} company /></>}
      {page === 'profile' && <section className="panel profile-panel"><div className="profile-hero"><Avatar person={user} /><div><h2>{user.name}</h2><p>{user.title}</p></div><span className="status approved">{label(user.role)}</span></div><dl className="profile-details">{[['Email address', user.email], ['Team', user.team], ['Manager', manager?.name || 'Not assigned'], ['Employment start date', fmt(user.start_date, { day: 'numeric', month: 'long', year: 'numeric' })], ['Annual entitlement', '28 calendar days'], ['Company time zone', workspace.company.timezone]].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p className="profile-hint">Need to update your details? Contact your HR team.</p></section>}
      {page === 'policy' && <div className="policy-layout"><section className="panel policy-content"><span className="eyebrow">THE SPACE TO SWITCH OFF</span><h2>Your time off, explained.</h2>{[['01', 'A little earned, every day', 'You earn 28 calendar days for each full calendar year of employment. Accrual begins on your start date and is calculated after each completed day, including weekends and leave. Leap years are accounted for.'], ['02', 'One long break. Or a few little ones.', 'Request one continuous period or split it into segments of at least one full day. Weekends and public holidays count. There is no mandatory 14-day segment.'], ['03', 'Your days stay yours', 'Unused entitlement carries forward without expiry. Requests use days you have already earned; future accrual cannot be borrowed. Pending requests reserve days until reviewed.'], ['04', 'A conversation with your manager', 'Your assigned manager approves or rejects the whole request with a comment. Only approved leave appears on team calendars. Requests awaiting review expire when the leave starts.'], ['05', 'Plans change. That’s okay.', 'Withdraw a pending request or cancel approved leave before any segment starts. To reschedule approved leave, submit replacement dates. Your existing dates remain approved until your manager accepts the change.']].map(([number, title, copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</section><div><section className="policy-highlight"><Sun size={32} strokeWidth={1.2} /><strong>28</strong><span>calendar days per year</span><p>For rest, adventure, family,<br />or absolutely no plans.</p></section><p className="policy-draft-note">Initial draft policy. Approval and change workflows can be refined as we shape Otpusk.</p></div></div>}
      <footer className="page-footer"><span><Sun size={14} />A little balance goes a long way.</span><span>Otpusk · Made for time well spent</span></footer>
    </main></div>
    {toast && <div className="toast" role="status"><Check size={18} />{toast}<button className="icon-button" aria-label="Dismiss message" onClick={() => setToast('')}><X size={16} /></button></div>}
    {modal?.type === 'request' && <RequestForm workspace={workspace} original={modal.original} close={() => setModal(null)} submit={body => mutation('/requests', body, body.replacesId ? 'New dates sent to your manager.' : 'Your time-off request is on its way.')} />}
    {modal?.type === 'review' && <ReviewForm request={modal.request} person={personFor(modal.request.employee_id)} close={() => setModal(null)} submit={body => mutation(`/requests/${modal.request.id}/review`, body, `Request ${body.status}. Your team is up to date.`)} />}
    {modal?.type === 'detail' && <Modal title={modal.request.replaces_id ? 'Schedule change' : 'Vacation leave'} subtitle={personFor(modal.request.employee_id)?.name} close={() => setModal(null)}><Status value={modal.request.status} /><div className="review-dates"><CalendarDays size={24} /><div><strong>{range(modal.request.segments)}</strong><p>{dayCount(modal.request.segments)} calendar days · {modal.request.segments.length} {modal.request.segments.length === 1 ? 'segment' : 'segments'}</p></div></div>{modal.request.note && <div className="detail-note"><span className="eyebrow">REQUEST NOTE</span><p>{modal.request.note}</p></div>}{modal.request.comment && <div className="detail-note"><span className="eyebrow">MANAGER’S COMMENT</span><p>{modal.request.comment}</p></div>}{modal.changePending && <p className="form-hint">A schedule change is awaiting approval. These dates remain approved.</p>}<div className="request-history"><h3>Request history</h3>{workspace.history.filter(h => h.request_id === modal.request.id).map(h => <div key={h.id}><span className="history-dot" /><div><strong>{h.action.split('_').map(label).join(' ')}</strong><span>{new Date(h.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}{personFor(h.actor_id) ? ` · ${personFor(h.actor_id).name}` : ''}</span></div></div>)}</div><div className="modal-actions">{modal.request.employee_id === user.id && modal.isFuture && ['approved', 'pending'].includes(modal.request.status) && <><button className="button danger" onClick={() => setModal({ type: 'cancel', request: modal.request })}>{modal.request.status === 'pending' ? 'Withdraw request' : 'Cancel leave'}</button>{modal.request.status === 'approved' && !modal.changePending && <button className="button primary" onClick={() => setModal({ type: 'request', original: modal.request })}>Reschedule<ArrowRight size={16} /></button>}</>}</div></Modal>}
    {modal?.type === 'cancel' && <Modal title={modal.request.status === 'pending' ? 'Withdraw this request?' : 'Cancel your time off?'} subtitle={range(modal.request.segments)} close={() => !actionBusy && setModal(null)}><p className="cancel-copy">Your days will return to your available balance. You can make a new request whenever you’re ready.</p>{modal.error && <p className="form-error" role="alert">{modal.error}</p>}<div className="modal-actions"><button className="button secondary" disabled={actionBusy} onClick={() => setModal(null)}>Keep my plans</button><button className="button danger" disabled={actionBusy} onClick={async () => { setActionBusy(true); try { await mutation(`/requests/${modal.request.id}/cancel`, {}, 'Your request was cancelled and your balance updated.'); } catch (error) { setModal({ ...modal, error: error.message }); } finally { setActionBusy(false); } }}>{actionBusy ? 'Updating…' : 'Yes, cancel request'}</button></div></Modal>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App />);
